#!/usr/bin/env python3
"""
plotJetMetricsTheory.py — publication-grade jet-observable figure comparing
the drill solver's on-the-fly log to the purely-inertial self-similar cone
theory (Gordillo, Rodriguez-Rodriguez & Sanjay, "Self-similar Worthington
jets"). Generalises the case-by-case scratch figures built earlier in this
project to an arbitrary number of cases/Oh values, reading directly from
solver `log` files (no pre-extracted CSVs needed).

## Theory

A conical cavity of semiangle beta collapses purely inertially. nu(beta) is
the smallest positive root of the Legendre condition P_nu(-cos(beta)) = 0
(this sign convention reproduces the paper's own Taylor-cone anchor
beta=49.3deg -> nu=0.5 — confirmed, do not flip the sign). alpha(beta) =
1/(2 - nu(beta)). Four local observables as functions of the instantaneous
jet-base radius r_j:

    q_j (r_j)  = v_j r_j            ~ r_j ^ ((2a-1)/a)   [flow rate / length]
    Q_j (r_j)  = pi r_j q_j         ~ r_j ^ ((3a-1)/a)   [flow rate feeding the jet]
    We_j(r_j)  = q_j^2 / r_j        ~ r_j ^ ((3a-2)/a)   [local Weber number]
    M_j (r_j)  = pi q_j^2           ~ r_j ^ ((4a-2)/a)   [momentum flux]

We_j is the paper's central result: it diverges as r_j -> 0 (purely
inertial), which rules out the classical inertio-capillary balance
(We_j = O(1) constant) once and for all — the We_j panel therefore also
draws that constant-value comparison.

## Mapping onto our simulation's raw solver log

The drill solver's `log` (simulationCases/<case>/log) carries, after two
header lines, whitespace-separated rows:
    i dt t ke maxlevel r_b z_b r_base z_base q_jet q_l
  - r_base is the jet-base radius r_j (the robust getBase probe; NOT r_b,
    which is the AMR-tracking probe and can latch onto satellites late in
    the jet phase).
  - q_jet = our INT u_z r dr is Q_j up to a constant prefactor (absorbed by
    the least-squares fit below — theory only fixes the SLOPE).
  - q_l   = our INT u_z dr   is q_j up to a constant prefactor, same story.
  - We_j and M_j are not logged directly: We_j = q_l^2 / r_base,
    M_j = q_l^2 (the pi is a constant, absorbed into the fitted prefactor).

## Usage

    python3 plotJetMetricsTheory.py \\
        --cases simulationCases/2001 simulationCases/2004 \\
        --out figures/oh_sweep_metrics

Each --cases entry is either a case DIRECTORY (containing `log` and,
optionally, `intermediate/` for the cone fit) or a bare `log` FILE. Facets
for the cone fit are auto-generated by shelling out to the compiled
`postProcess/getFacet` binary against the snapshot nearest each case's
inception time; pass --facets to supply pre-extracted "z r" dumps instead
(useful when getFacet isn't available locally, e.g. previewing on macOS).

@author Vatsal Sanjay (vatsal.sanjay@comphy-lab.org) / CoMPhy Lab
"""
import os
import re
import sys
import glob
import math
import argparse
import subprocess as sp

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.ticker import FixedLocator, FuncFormatter

matplotlib.rcParams["font.family"] = "serif"
matplotlib.rcParams["font.serif"] = ["Computer Modern Roman"]
matplotlib.rcParams["text.usetex"] = True
matplotlib.rcParams["text.latex.preamble"] = r"\usepackage{amsmath}"

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
GETFACET = os.path.join(SCRIPT_DIR, "getFacet")

# Okabe-Ito colourblind-safe categorical palette (used for <=4 cases; a
# continuous colormap keyed by Oh is used for larger sweeps).
CAT_PALETTE = ["#0072B2", "#E69F00", "#D55E00", "#009E73",
               "#CC79A7", "#56B4E9", "#F0E442", "#000000"]


# ============================== Legendre / cone-fit math ====================
# Copied verbatim from postProcess/conefit.py (same file, validated multiple
# times against the paper's Taylor-cone anchor beta=49.3 -> nu=0.5). Kept
# duplicated rather than imported so this script has no import-path
# dependency on being run from a specific working directory.

def _linfit(xs, ys):
    n = len(xs)
    sx = sum(xs)
    sy = sum(ys)
    sxx = sum(x * x for x in xs)
    sxy = sum(x * y for x, y in zip(xs, ys))
    m = (n * sxy - sx * sy) / (n * sxx - sx * sx)
    c = (sy - m * sx) / n
    yb = sy / n
    ss_tot = sum((y - yb) ** 2 for y in ys)
    ss_res = sum((y - (m * x + c)) ** 2 for x, y in zip(xs, ys))
    r2 = 1 - ss_res / ss_tot if ss_tot > 0 else 0.0
    return m, c, r2


def _P_nu(nu, x):
    """Legendre P_nu(x) via the Gauss hypergeometric series 2F1(-nu,nu+1;1;(1-x)/2)."""
    z = (1.0 - x) / 2.0
    a, b, c = -nu, nu + 1.0, 1.0
    term = 1.0
    s = 1.0
    for n in range(1, 2000):
        term *= (a + n - 1) * (b + n - 1) / ((c + n - 1) * n) * z
        s += term
        if abs(term) < 1e-15 * max(1.0, abs(s)):
            break
    return s


def _solve_nu(beta_deg):
    """Smallest positive root of P_nu(-cos(beta)) = 0 (cone surface condition)."""
    x = -math.cos(math.radians(beta_deg))
    step = 0.005
    nu = step
    fprev = _P_nu(nu, x)
    lo = None
    while nu < 2.0:
        nu2 = nu + step
        f2 = _P_nu(nu2, x)
        if fprev * f2 <= 0:
            lo, hi, flo = nu, nu2, fprev
            break
        nu, fprev = nu2, f2
    if lo is None:
        return None
    for _ in range(200):
        mid = 0.5 * (lo + hi)
        fm = _P_nu(mid, x)
        if flo * fm <= 0:
            hi = mid
        else:
            lo, flo = mid, fm
    return 0.5 * (lo + hi)


# ============================== log / facet parsing ==========================

def parse_log(path):
    """Parse a drill-solver `log` file into a structured array + the header Oh.

    Returns (rows, oh) where rows is an (N,7) float array of columns
    [t, r_base, z_base, q_jet, q_l, maxlevel, r_b], time-ordered, with
    sentinel (-1000) and restart-overlap duplicate rows removed.
    """
    oh = None
    raw = []
    with open(path) as fh:
        for ln in fh:
            if oh is None:
                m = re.search(r"Oh\s+([0-9.eE+-]+)", ln)
                if m:
                    oh = float(m.group(1))
            p = ln.split()
            if not p:
                continue
            try:
                int(p[0])
            except ValueError:
                continue
            if len(p) < 11:
                continue
            try:
                t, ml = float(p[2]), int(p[4])
                r_b, z_b = float(p[5]), float(p[6])
                r_base, z_base = float(p[7]), float(p[8])
                q_jet, q_l = float(p[9]), float(p[10])
            except ValueError:
                continue
            if r_base <= -900 or z_base <= -900:
                continue
            raw.append((t, r_base, z_base, q_jet, q_l, ml, r_b))

    if not raw:
        raise SystemExit("plotJetMetricsTheory: no numeric rows parsed from %s" % path)

    # Restart-overlap de-dup: a mid-run restart re-writes rows for t ranges
    # already present earlier in the file. Sort by t, then for repeated t
    # values keep the LAST occurrence found in file order (the most recent
    # restart's data), by simply overwriting a dict keyed on rounded t.
    keyed = {}
    for i, row in enumerate(raw):
        keyed[round(row[0], 8)] = row
    rows = np.array(sorted(keyed.values(), key=lambda r: r[0]))
    return rows, oh


def reconnection_time(rows, pin_r=0.005, t_min=0.40):
    """Last t where the base is still pinned on-axis, t > t_min.

    This marks the end of the singular focusing approach; the jet exists
    only for t beyond this point. More robust than a fixed constant since
    reconnection time shifts with Oh.
    """
    t, r_base = rows[:, 0], rows[:, 1]
    mask = (t > t_min) & (r_base < pin_r)
    if not mask.any():
        return None
    return float(t[mask].max())


def jet_phase_rows(rows, incept_t, rmin=0.04):
    t, r_base, q_jet, q_l = rows[:, 0], rows[:, 1], rows[:, 3], rows[:, 4]
    mask = (t > incept_t) & (r_base > rmin) & (q_jet > 0) & (q_l > 0)
    return rows[mask]


def facet_points_from_file(path):
    pts = []
    with open(path) as fh:
        for ln in fh:
            s = ln.split()
            if len(s) == 2:
                try:
                    z, r = float(s[0]), float(s[1])
                    if r > 0:
                        pts.append((z, r))
                except ValueError:
                    pass
    return pts


def facet_points_from_case(case_dir, snap_t):
    snaps = glob.glob(os.path.join(case_dir, "intermediate", "snapshot-*"))
    if not snaps:
        return None
    rel = os.path.relpath(
        min(snaps, key=lambda f: abs(float(f.rsplit("snapshot-", 1)[-1]) - snap_t)),
        case_dir)
    if not os.path.exists(GETFACET):
        return None
    p = sp.Popen([GETFACET, rel], cwd=case_dir, stdout=sp.PIPE, stderr=sp.PIPE)
    out, _ = p.communicate()
    pts = []
    for ln in out.decode(errors="ignore").split("\n"):
        s = ln.split()
        if len(s) == 2:
            try:
                z, r = float(s[0]), float(s[1])
                if r > 0:
                    pts.append((z, r))
            except ValueError:
                pass
    return pts


def cone_fit(pts, zlo, zhi, rlo, rhi):
    wall = [(z, r) for (z, r) in pts if zlo <= z <= zhi and rlo <= r <= rhi]
    if len(wall) < 2:
        return None
    zs = [z for z, r in wall]
    rs = [r for z, r in wall]
    m, c, r2 = _linfit(zs, rs)
    beta = math.degrees(math.atan(m))
    nu = _solve_nu(beta)
    if nu is None:
        return None
    alpha = 1.0 / (2.0 - nu)
    z_apex = -c / m
    return dict(beta=beta, nu=nu, alpha=alpha, slope=m, z_apex=z_apex,
                r2=r2, n=len(wall), pts=pts)


# ============================== fitting / plotting helpers ===================

def powerfit_fixed_slope(r, q, slope, rlo, rhi):
    """Least-squares log-space prefactor for q = K * r^slope over [rlo,rhi]."""
    m = (r >= rlo) & (r <= rhi) & (q > 0)
    if m.sum() < 2:
        return None, int(m.sum())
    logK = np.mean(np.log(q[m]) - slope * np.log(r[m]))
    return math.exp(logK), int(m.sum())


def thin_logspace(r, *arrs, n=250):
    idx = np.argsort(r)
    r = r[idx]
    arrs = [a[idx] for a in arrs]
    if len(r) <= n:
        return (r,) + tuple(arrs)
    lo, hi = np.log10(r.min()), np.log10(r.max())
    targets = np.logspace(lo, hi, n)
    keep = np.unique(np.searchsorted(r, targets).clip(0, len(r) - 1))
    return (r[keep],) + tuple(a[keep] for a in arrs)


def nice_ticks(vmin, vmax):
    candidates = [1e-3, 2e-3, 3e-3, 5e-3, 1e-2, 2e-2, 3e-2, 5e-2,
                  0.1, 0.2, 0.3, 0.5, 1, 2, 3, 5, 10, 20, 30, 50, 100, 200, 500, 1000]
    ticks = [c for c in candidates if vmin * 0.9 <= c <= vmax * 1.1]
    if len(ticks) < 3:
        ticks = list(np.geomspace(vmin, vmax, 4))
    return ticks


def style_log_axis(ax, xlim, ylim):
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlim(*xlim)
    ax.set_ylim(*ylim)
    fmt = FuncFormatter(lambda v, _: f"{v:g}")
    xt = nice_ticks(*xlim)
    yt = nice_ticks(*ylim)
    ax.xaxis.set_major_locator(FixedLocator(xt))
    ax.xaxis.set_minor_locator(FixedLocator([]))
    ax.yaxis.set_major_locator(FixedLocator(yt))
    ax.yaxis.set_minor_locator(FixedLocator([]))
    ax.xaxis.set_major_formatter(fmt)
    ax.yaxis.set_major_formatter(fmt)
    ax.tick_params(which="major", direction="out", width=1.6, length=7, labelsize=13, pad=5)
    ax.tick_params(which="minor", length=0)
    for sp_ in ax.spines.values():
        sp_.set_linewidth(1.6)


# ==================================== main ====================================

def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--cases", nargs="+", required=True,
                     help="Case directories (containing `log`) or bare log files.")
    ap.add_argument("--labels", nargs="+", default=None,
                     help="Legend labels, one per --cases entry (default: Oh=<value> "
                          "parsed from each log's header line).")
    ap.add_argument("--facets", nargs="+", default=None,
                     help="Pre-extracted 'z r' facet dump files for the cone fit, one "
                          "per --cases entry (overrides auto-running getFacet).")
    ap.add_argument("--incept-t", nargs="+", type=float, default=None, dest="incept_t",
                     help="Override reconnection/inception time per case (else "
                          "auto-detected: last t>0.40 with r_base<0.005).")
    ap.add_argument("--fit-window", nargs=2, type=float, default=[0.042, 0.08],
                     dest="fit_window",
                     help="r_j window for the theory prefactor least-squares fit "
                          "(the tau->0 asymptote; excludes the startup transient).")
    ap.add_argument("--cone-window", nargs=4, type=float,
                     default=[-1.60, -0.40, 0.10, 1.00], dest="cone_window",
                     metavar=("ZLO", "ZHI", "RLO", "RHI"),
                     help="Facet-cloud window for the cone linear fit.")
    ap.add_argument("--out", required=True, help="Output path stem (writes .png and .pdf).")
    args = ap.parse_args()

    n_cases = len(args.cases)
    labels = args.labels if args.labels else [None] * n_cases
    facets_in = args.facets if args.facets else [None] * n_cases
    incepts_in = args.incept_t if args.incept_t else [None] * n_cases
    if len(labels) != n_cases or len(facets_in) != n_cases or len(incepts_in) != n_cases:
        raise SystemExit("plotJetMetricsTheory: --labels/--facets/--incept-t must each "
                          "have the same length as --cases (or be omitted).")

    zlo, zhi, rlo_c, rhi_c = args.cone_window
    fit_rlo, fit_rhi = args.fit_window

    cases = []
    for i, c in enumerate(args.cases):
        case_dir = c if os.path.isdir(c) else os.path.dirname(os.path.abspath(c))
        log_path = c if os.path.isfile(c) else os.path.join(c, "log")
        if not os.path.exists(log_path):
            raise SystemExit("plotJetMetricsTheory: no log file found for --cases entry %r" % c)

        rows, oh = parse_log(log_path)
        incept_t = incepts_in[i] if incepts_in[i] is not None else reconnection_time(rows)
        if incept_t is None:
            raise SystemExit("plotJetMetricsTheory: could not detect reconnection time for "
                              "%s — pass --incept-t explicitly." % c)
        jet = jet_phase_rows(rows, incept_t)
        if jet.shape[0] < 5:
            raise SystemExit("plotJetMetricsTheory: only %d jet-phase rows found for %s "
                              "(incept_t=%.4f) — check the case ran past inception."
                              % (jet.shape[0], c, incept_t))

        r_j = jet[:, 1]
        q_j = jet[:, 4]        # our q_l
        Q_j = jet[:, 3]        # our q_jet
        We_j = q_j ** 2 / r_j
        M_j = q_j ** 2

        # cone fit
        if facets_in[i] is not None:
            pts = facet_points_from_file(facets_in[i])
        else:
            pts = facet_points_from_case(case_dir, incept_t)
        cone = cone_fit(pts, zlo, zhi, rlo_c, rhi_c) if pts else None

        label = labels[i] if labels[i] else (r"$Oh=%.4g$" % oh if oh is not None else c)

        cases.append(dict(name=c, oh=oh, label=label, incept_t=incept_t,
                           r_j=r_j, q_j=q_j, Q_j=Q_j, We_j=We_j, M_j=M_j, cone=cone))

    # --- colours: categorical for small N, colour-by-Oh continuous for large sweeps
    ohs = [c["oh"] if c["oh"] is not None else i for i, c in enumerate(cases)]
    if n_cases <= len(CAT_PALETTE):
        colours = CAT_PALETTE[:n_cases]
    else:
        order = np.argsort(ohs)
        cmap = plt.get_cmap("viridis")
        colours = [None] * n_cases
        for rank, idx in enumerate(order):
            colours[idx] = cmap(rank / max(1, n_cases - 1))

    # --- console diagnostics ---------------------------------------------------
    print("=== plotJetMetricsTheory: per-case cone fit + theory exponents ===")
    for c in cases:
        cone = c["cone"]
        if cone is None:
            print("  %-28s incept_t=%.4f  n_jet=%d  CONE FIT FAILED (no facet data)"
                  % (c["label"], c["incept_t"], c["r_j"].size))
            continue
        a = cone["alpha"]
        e_qj = (2 * a - 1) / a
        e_Qj = (3 * a - 1) / a
        e_We = (3 * a - 2) / a
        e_Mj = (4 * a - 2) / a
        c["exponents"] = dict(q_j=e_qj, Q_j=e_Qj, We_j=e_We, M_j=e_Mj)
        print("  %-28s incept_t=%.4f  n_jet=%d" % (c["label"], c["incept_t"], c["r_j"].size))
        print("      beta=%.2fdeg  nu=%.4f  alpha=%.4f  (cone fit R^2=%.4f, n=%d pts)"
              % (cone["beta"], cone["nu"], a, cone["r2"], cone["n"]))
        print("      theory: q_j~r^%.3f  Q_j~r^%.3f  We_j~r^%.3f  M_j~r^%.3f"
              % (e_qj, e_Qj, e_We, e_Mj))

    # --- figure ------------------------------------------------------------
    fig, axes = plt.subplots(2, 2, figsize=(12.5, 10.5))
    (ax_qj, ax_Qj), (ax_We, ax_Mj) = axes

    panels = [
        (ax_qj, "q_j", r"$q_j = v_j r_j$", "a"),
        (ax_Qj, "Q_j", r"$Q_j = \pi r_j q_j$", "b"),
        (ax_We, "We_j", r"$We_j = q_j^2/r_j$", "c"),
        (ax_Mj, "M_j", r"$M_j = \pi q_j^2$", "d"),
    ]

    legend_handles = []
    legend_labels = []
    for ax, key, ylabel, tag in panels:
        for c, colour in zip(cases, colours):
            r_j = c["r_j"]
            q = c[key]
            rt, qt = thin_logspace(r_j, q, n=250)
            h, = ax.plot(rt, qt, "o", ms=4.0 if n_cases > 4 else 5.5, mfc=colour, mec="k",
                          mew=0.3, lw=0, zorder=3)
            if ax is ax_qj:
                legend_handles.append(h)
                legend_labels.append(c["label"])

            if c.get("exponents") is None:
                continue
            slope = c["exponents"][key]
            K, nfit = powerfit_fixed_slope(r_j, q, slope, fit_rlo, fit_rhi)
            if K is None:
                continue
            rline = np.geomspace(r_j.min() * 0.9, r_j.max() * 1.05, 40)
            ax.plot(rline, K * rline ** slope, "-", color=colour, lw=1.6, alpha=0.85, zorder=2)

        # inertio-capillary comparison on the We_j panel: classical balance
        # predicts We_j = O(1) constant, independent of r_j.
        if key == "We_j":
            all_r = np.concatenate([c["r_j"] for c in cases])
            rline = np.geomspace(all_r.min() * 0.9, all_r.max() * 1.05, 10)
            hic, = ax.plot(rline, np.ones_like(rline), "--", color="0.35", lw=1.8, zorder=1)
            legend_handles.append(hic)
            legend_labels.append(r"inertio-capillary ($We_j=O(1)$)")

        all_r = np.concatenate([c["r_j"] for c in cases])
        all_q = np.concatenate([c[key] for c in cases])
        style_log_axis(ax, (all_r.min() * 0.85, all_r.max() * 1.2),
                        (all_q.min() * 0.7, all_q.max() * 1.4))
        ax.set_xlabel(r"$r_j$", fontsize=17, labelpad=6)
        ax.set_ylabel(ylabel, fontsize=17, labelpad=8)
        ax.text(-0.02, 1.05, r"(%s)" % tag, transform=ax.transAxes, fontsize=17,
                va="top", ha="right")

    ax_We.legend(legend_handles, legend_labels, fontsize=10.5, loc="lower left",
                 frameon=False, handletextpad=0.4)

    # --- inset: only meaningful for a small number of cases -------------------
    cone_cases = [c for c in cases if c["cone"] is not None]
    if n_cases <= 2 and cone_cases:
        c0 = cone_cases[0]
        cone = c0["cone"]
        pts = np.array(cone["pts"])
        fz, fr = pts[:, 0], pts[:, 1]
        axin = ax_qj.inset_axes([0.06, 0.55, 0.34, 0.32])
        # cavity+jet region only — the raw facet dump also carries the flat
        # outer free surface out to the domain radius (r up to ~10), which
        # would swamp autoscaling; cap explicitly and set limits by hand.
        z_lo = fz.min() - 0.05
        z_hi = min(float(fz.max()), 0.30)
        r_hi = min(float(fr.max()), 1.30)
        zwin = (fz >= z_lo) & (fz <= z_hi) & (fr <= r_hi)
        axin.plot(fr[zwin], fz[zwin], ".", color="green", ms=1.4, lw=0, zorder=2)
        axin.plot(-fr[zwin], fz[zwin], ".", color="green", ms=1.4, lw=0, zorder=2)
        zl = np.array([cone["z_apex"], zhi])
        rl = cone["slope"] * zl + (-cone["slope"] * cone["z_apex"])
        axin.plot(rl, zl, "--", color="#C81E1E", lw=1.4, zorder=3)
        axin.plot(-rl, zl, "--", color="#C81E1E", lw=1.4, zorder=3)
        axin.plot([0, 0], [z_lo, z_hi], "-.", color="grey", lw=0.9, zorder=1)
        axin.set_xlim(-r_hi, r_hi)
        axin.set_ylim(z_lo, z_hi)
        axin.set_aspect("equal")
        axin.set_xticks([])
        axin.set_yticks([])
        for sp_ in axin.spines.values():
            sp_.set_linewidth(1.0)
        ax_qj.text(0.045, 0.975,
                    r"$\beta=%.1f^\circ,\ \nu=%.2f,\ \alpha=%.2f$"
                    % (cone["beta"], cone["nu"], cone["alpha"]),
                    transform=ax_qj.transAxes, fontsize=12.5, va="top", ha="left")
    elif cone_cases:
        # many cases: a compact beta/alpha summary instead of a single inset
        lines = [r"$\beta,\alpha$ per case:"]
        for c in cone_cases[:8]:
            lines.append(r"%s: $\beta{=}%.1f^\circ,\alpha{=}%.2f$"
                          % (c["label"], c["cone"]["beta"], c["cone"]["alpha"]))
        ax_qj.text(0.045, 0.975, "\n".join(lines), transform=ax_qj.transAxes,
                    fontsize=8.5, va="top", ha="left")

    fig.suptitle(r"$Bo = 10^{-3}$" +
                  (r"$,\ Oh = %.4g$" % cases[0]["oh"] if n_cases == 1 and cases[0]["oh"] else ""),
                  fontsize=14, y=0.995)
    plt.tight_layout(w_pad=2.6, h_pad=2.4, rect=(0, 0, 1, 0.97))
    plt.savefig(args.out + ".png", dpi=300, bbox_inches="tight", pad_inches=0.08)
    plt.savefig(args.out + ".pdf", dpi=300, bbox_inches="tight", pad_inches=0.08)
    plt.close(fig)
    print("\nWROTE: %s.png" % args.out)
    print("WROTE: %s.pdf" % args.out)


if __name__ == "__main__":
    main()
